version: '3.8'
services:
  task-manager:
    image: task-manager:latest
    ports:
      - "8080:8080"
    networks:
      - my_network

  task-notification:
    image: task-notification:latest
    ports:
      - "8081:8081"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge